data_ingestion:
  download_url: https://www.kaggle.com/datasets/alessiocorrado99/animals10
  local_data_file: data/
  images_loc: data/animals10/raw-img/

model_training_config:
  device: dml
  learning_rate: 0.01
  momentum: 0.952
  w_decay: 0.001
  batch_size: 16
  epochs: 15
  train_size: 0.8

model_inference_file:
  file_path: dog.jpg
